/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_catherineliu_practice_about_test_myJNI */

#ifndef _Included_com_catherineliu_practice_about_test_myJNI
#define _Included_com_catherineliu_practice_about_test_myJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_catherineliu_practice_about_test_myJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_catherineliu_practice_about_1test_myJNI_sayHello
  (JNIEnv *env, jclass jobj){
        return (*env)->NewStringUTF(env,"Hello jni!");
  }

#ifdef __cplusplus
}
#endif
#endif